/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHotifications: typeof import('./../src/components/AppHotifications.vue')['default']
    ComponentIcon: typeof import('./../src/assets/svg/ComponentIcon.vue')['default']
    ConstructorSettings: typeof import('./../src/components/ConstructorSettings.vue')['default']
    ConstructorView: typeof import('./../src/components/ConstructorView.vue')['default']
    CreateIcon: typeof import('./../src/assets/svg/CreateIcon.vue')['default']
    EmailIcon: typeof import('./../src/assets/svg/EmailIcon.vue')['default']
    GitHubIcon: typeof import('./../src/assets/svg/GitHubIcon.vue')['default']
    HeartIcon: typeof import('./../src/assets/svg/HeartIcon.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    HomeSection: typeof import('./../src/components/HomeView/HomeSection.vue')['default']
    IconCommunity: typeof import('./../src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../src/components/icons/IconTooling.vue')['default']
    InfoIcon: typeof import('./../src/assets/svg/InfoIcon.vue')['default']
    NavContacts: typeof import('./../src/components/Navbar/NavContacts.vue')['default']
    NavGalleryOptions: typeof import('./../src/components/Navbar/NavGalleryOptions.vue')['default']
    NavMenuIcon: typeof import('./../src/components/Navbar/NavMenuIcon.vue')['default']
    NavMobMenu: typeof import('./../src/components/Navbar/NavMobMenu.vue')['default']
    NavThemeSwitcher: typeof import('./../src/components/Navbar/NavThemeSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TelegramIcon: typeof import('./../src/assets/svg/TelegramIcon.vue')['default']
    TemplatesSection: typeof import('./../src/components/HomeView/TemplatesSection.vue')['default']
    TheCopyright: typeof import('./../src/components/HomeView/TheCopyright.vue')['default']
    TheHomeSection: typeof import('./../src/components/HomeView/TheHomeSection.vue')['default']
    TheLibrarySection: typeof import('./../src/components/HomeView/TheLibrarySection.vue')['default']
    TheNavbar: typeof import('./../src/components/Navbar/TheNavbar.vue')['default']
    TheSelect: typeof import('./../src/components/TheSelect.vue')['default']
    TheTemplate: typeof import('./../src/components/HomeView/TheTemplate.vue')['default']
    TheTemplatesSection: typeof import('./../src/components/HomeView/TheTemplatesSection.vue')['default']
    TheWelcome: typeof import('./../src/components/TheWelcome.vue')['default']
    TranslateIcon: typeof import('./../src/assets/svg/TranslateIcon.vue')['default']
    WelcomeItem: typeof import('./../src/components/WelcomeItem.vue')['default']
  }
}
