/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const axios: typeof import('axios')['default']
  const computed: typeof import('vue')['computed']
  const inject: typeof import('vue')['inject']
  const onMounted: typeof import('vue')['onMounted']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const useDark: typeof import('@vueuse/core')['useDark']
  const useEventListener: typeof import('@vueuse/core')['useEventListener']
  const useImage: typeof import('@vueuse/core')['useImage']
  const useNavigatorLanguage: typeof import('@vueuse/core')['useNavigatorLanguage']
  const useResizeObserver: typeof import('@vueuse/core')['useResizeObserver']
  const useStorage: typeof import('@vueuse/core')['useStorage']
  const watch: typeof import('vue')['watch']
}
